// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Unique identifier using KSUID format with a resource-specific prefix.
 */
export const zKsuid = z.string().regex(/^[a-z_]{2,20}_[0-9a-zA-Z]{27}$/);

export const zApiError = z.object({
    code: z.string(),
    message: z.string(),
    field: z.optional(z.string()),
    details: z.optional(z.record(z.string(), z.unknown()))
});

export const zApiErrorResponse = z.object({
    errors: z.array(zApiError)
});

export const zPagedListResponse = z.object({
    total: z.coerce.bigint(),
    count: z.int()
});

export const zPaginationRequest = z.object({
    limit: z.optional(z.int().gte(1).lte(100)).default(20),
    offset: z.optional(z.int().gte(0)).default(0)
});

export const zSortDirection = z.enum([
    'ASC',
    'DESC'
]);

/**
 * Generic search request template
 */
export const zSearchRequest = z.object({
    pagination: z.optional(zPaginationRequest),
    full_text_search: z.optional(z.string()),
    sort_direction: z.optional(zSortDirection)
});

/**
 * Optional key-value metadata. Values can be string, number, boolean.
 */
export const zMetadata = z.record(z.string(), z.unknown());

export const zAuthTokenResponse = z.object({
    accessToken: z.string(),
    refreshToken: z.string()
});

export const zLoginRequest = z.object({
    email: z.email(),
    password: z.string()
});

export const zRegisterRequest = z.object({
    email: z.email(),
    password: z.string(),
    invitation_code: z.optional(z.string()),
    tenant_name: z.optional(z.string().min(2).max(100))
});

export const zPlatformInvitationRequest = z.object({
    email: z.email()
});

export const zPlatformInvitationResponse = z.object({
    id: zKsuid,
    code: z.string(),
    email: z.email(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    tenant_id: zKsuid
});

export const zPlatformInvitationListResponse = zPagedListResponse.and(z.object({
    items: z.array(zPlatformInvitationResponse)
}));

export const zPlatformInvitationFilter = z.object({
    emails: z.optional(z.array(z.email())),
    ids: z.optional(z.array(zKsuid))
});

export const zPlatformInvitationSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zPlatformInvitationFilter),
    sort_by: z.optional(z.enum([
        'email',
        'created_at',
        'updated_at'
    ]))
}));

/**
 * The role of the platform user.
 */
export const zPlatformUserRole = z.enum([
    'OWNER',
    'ADMIN'
]);

export const zPlatformUserResponse = z.object({
    id: zKsuid,
    user_id: zKsuid,
    email: z.email(),
    role: zPlatformUserRole,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    tenant_id: zKsuid
});

export const zPlatformUserFilter = z.object({
    emails: z.optional(z.array(z.email())),
    roles: z.optional(z.array(zPlatformUserRole)),
    ids: z.optional(z.array(zKsuid))
});

export const zPlatformUserSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zPlatformUserFilter),
    sort_by: z.optional(z.enum([
        'email',
        'created_at',
        'updated_at',
        'role'
    ]))
}));

export const zPlatformUserListResponse = zPagedListResponse.and(z.object({
    items: z.array(zPlatformUserResponse)
}));

export const zProductFilter = z.object({
    names: z.optional(z.array(z.string())),
    ids: z.optional(z.array(zKsuid))
});

export const zProductSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zProductFilter),
    sort_by: z.optional(z.enum([
        'name',
        'created_at',
        'updated_at'
    ]))
}));

export const zProductRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.optional(z.union([
        z.string().max(1000),
        z.null()
    ]))
});

export const zProductResponse = z.object({
    id: zKsuid,
    tenant_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductResponse)
}));

/**
 * A built-in permission that controls access to the product itself within Anchor (e.g. product:settings:read, product:billing:update). These permissions are system-defined — they cannot be created or deleted via the API. Use the search endpoint to discover which permissions are available for a product.
 */
export const zProductPermissionResponse = z.object({
    product_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductPermissionListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductPermissionResponse)
}));

/**
 * Request body for defining a new domain-resource permission for the product's own application resources. For example, if you are building a Google Drive-like product you might define permissions such as "document:read", "document:create", or "file:delete". These permissions are later assigned to ProductRoles, which are attached to end-user organization memberships.
 */
export const zCreateProductResourcePermissionRequest = z.object({
    name: z.string().min(2).max(200),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    scope_modifier: z.optional(z.union([
        z.string().max(100),
        z.null()
    ]))
});

/**
 * Request body for updating a product resource permission's metadata.
 */
export const zUpdateProductResourcePermissionRequest = z.object({
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ]))
});

/**
 * A domain-resource permission defined by the product owner for their own application resources. These permissions are created by the product (e.g. "document:read", "file:delete" for a Google Drive-like product) and assigned to ProductRoles. They control what end-users can do *inside the product*, as opposed to ProductPermissions which control access to the product itself within Anchor.
 */
export const zProductResourcePermissionResponse = z.object({
    product_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    scope_modifier: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductResourcePermissionFilter = z.object({
    names: z.optional(z.array(z.string()))
});

export const zProductResourcePermissionSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zProductResourcePermissionFilter),
    sort_by: z.optional(z.enum([
        'created_at',
        'updated_at',
        'name'
    ]))
}));

export const zProductResourcePermissionListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductResourcePermissionResponse)
}));

export const zProductRoleCreateRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    permissions: z.optional(z.array(z.string()))
});

export const zProductRoleUpdateRequest = z.object({
    name: z.optional(z.string().min(2).max(100)),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    permissions: z.optional(z.array(z.string()))
});

/**
 * Represents a product resource permission (e.g. "document:read") that has been assigned to a ProductRole. These are domain-specific permissions defined by the product owner for their own application resources, not to be confused with the built-in ProductPermissions that govern access to the product within Anchor.
 */
export const zProductRolePermissionResponse = z.object({
    product_id: zKsuid,
    permission_name: z.string(),
    product_role_id: zKsuid
});

export const zProductRoleResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    permissions: z.array(zProductRolePermissionResponse),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductRoleListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductRoleResponse)
}));

export const zProductPermissionsResponse = z.object({
    permissions: z.array(zProductPermissionResponse)
});

/**
 * Request body for assigning a product resource permission to a role. The permission must already exist under the product's resource permissions (see /resource-permissions endpoints).
 */
export const zAssignPermissionRequest = z.object({
    permission_name: z.string()
});

export const zProductApiKeyStatus = z.enum([
    'ACTIVE',
    'INACTIVE'
]);

export const zProductApiKeyCreateRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    mutable: z.optional(z.boolean()).default(false),
    permissions: z.optional(z.array(z.string()))
});

/**
 * Represents a Anchor built-in scope granted to a Product API Key. These are the operational permissions that control what the product backend can do within Anchor itself (e.g. "organization:create", "product_user:read"). Not to be confused with ProductResourcePermissions, which are domain-specific permissions defined by the product owner for their own end-users.
 */
export const zProductApiKeyPermissionResponse = z.object({
    product_id: zKsuid,
    permission_name: z.string(),
    product_api_key_id: zKsuid
});

export const zProductApiKeyResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    mutable: z.boolean(),
    obfuscated_value: z.string(),
    expires_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    last_used_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    permissions: z.array(zProductApiKeyPermissionResponse),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    status: zProductApiKeyStatus
});

export const zCreatedProductApiKeyResponse = zProductApiKeyResponse.and(z.object({
    value: z.string()
}));

export const zProductApiKeyListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductApiKeyResponse)
}));

export const zOrganizationApiKeyStatus = z.enum([
    'ACTIVE',
    'INACTIVE'
]);

export const zOrganizationApiKeyCreateRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    expires_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    permissions: z.array(z.string())
});

/**
 * Represents a Anchor built-in scope granted to an Organization API Key.
 */
export const zOrganizationApiKeyPermissionResponse = z.object({
    organization_id: zKsuid,
    product_id: zKsuid,
    permission_name: z.string(),
    organization_api_key_id: zKsuid
});

export const zOrganizationApiKeyResponse = z.object({
    id: zKsuid,
    organization_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    obfuscated_value: z.string(),
    expires_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    last_used_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    permissions: z.array(zOrganizationApiKeyPermissionResponse),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    status: zOrganizationApiKeyStatus
});

export const zCreatedOrganizationApiKeyResponse = zOrganizationApiKeyResponse.and(z.object({
    value: z.string()
}));

export const zOrganizationApiKeyListResponse = zPagedListResponse.and(z.object({
    items: z.array(zOrganizationApiKeyResponse)
}));

/**
 * The status of the product Product User account.
 */
export const zProductUserStatus = z.enum([
    'active',
    'invited',
    'suspended'
]);

export const zProductUserRequest = z.object({
    email: z.optional(z.email()),
    name: z.optional(z.union([
        z.string().min(1).max(100),
        z.null()
    ])),
    status: z.optional(zProductUserStatus)
});

export const zProductUserResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    email: z.email(),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    external_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: zProductUserStatus,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductUserListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductUserResponse)
}));

/**
 * Filter criteria for searching built-in product permissions.
 */
export const zProductPermissionFilter = z.object({
    names: z.optional(z.array(z.string()))
});

export const zProductRoleFilter = z.object({
    ids: z.optional(z.array(zKsuid)),
    names: z.optional(z.array(z.string())),
    name_contains: z.optional(z.string())
});

export const zProductApiKeyFilter = z.object({
    ids: z.optional(z.array(zKsuid)),
    names: z.optional(z.array(z.string())),
    status: z.optional(z.array(zProductApiKeyStatus)),
    expires_before: z.optional(z.iso.datetime()),
    expires_after: z.optional(z.iso.datetime())
});

export const zOrganizationApiKeyFilter = z.object({
    ids: z.optional(z.array(zKsuid)),
    names: z.optional(z.array(z.string())),
    status: z.optional(z.array(zOrganizationApiKeyStatus)),
    last_used_before: z.optional(z.iso.datetime()),
    last_used_after: z.optional(z.iso.datetime())
});

export const zWorkspaceMembershipFilter = z.object({
    workspace_ids: z.optional(z.array(zKsuid)),
    organization_ids: z.optional(z.array(zKsuid)),
    product_user_ids: z.optional(z.array(zKsuid)),
    user_emails: z.optional(z.array(z.email())),
    product_role_ids: z.optional(z.array(zKsuid)),
    role_names: z.optional(z.array(z.string()))
});

export const zOrganizationFilter = z.object({
    ids: z.optional(z.array(zKsuid)),
    names: z.optional(z.array(z.string()))
});

export const zWorkspaceFilter = z.object({
    ids: z.optional(z.array(zKsuid)),
    names: z.optional(z.array(z.string()))
});

export const zProductUserFilter = z.object({
    ids: z.optional(z.array(zKsuid)),
    emails: z.optional(z.array(z.email())),
    names: z.optional(z.array(z.string())),
    statuses: z.optional(z.array(zProductUserStatus)),
    external_ids: z.optional(z.array(z.string()))
});

export const zProductUserSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zProductUserFilter),
    sort_by: z.optional(z.enum([
        'email',
        'name',
        'status',
        'created_at',
        'updated_at'
    ]))
}));

/**
 * Optional include parameter for user organization endpoints.
 */
export const zUserOrganizationInclude = z.enum([
    'role_permissions'
]);

/**
 * The user's role within an organization.
 */
export const zUserOrganizationRoleResponse = z.object({
    id: zKsuid,
    name: z.string(),
    permissions: z.optional(z.array(z.string()))
});

/**
 * Organization details from the perspective of a product user, including their membership and role.
 */
export const zUserOrganizationResponse = z.object({
    organization: z.object({
        id: zKsuid,
        name: z.string(),
        description: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        metadata: z.optional(zMetadata)
    }),
    role: zUserOrganizationRoleResponse,
    joined_at: z.iso.datetime()
});

/**
 * Request body for adding a product user to an organization with a specific role.
 */
export const zOrganizationMembershipRequest = z.object({
    organization_id: zKsuid,
    role_id: zKsuid
});

/**
 * Request body for updating a product user's role within an organization.
 */
export const zOrganizationMembershipUpdateRequest = z.object({
    role_id: zKsuid
});

export const zUserOrganizationListResponse = z.object({
    items: z.array(zUserOrganizationResponse)
});

export const zProductPermissionSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zProductPermissionFilter),
    sort_by: z.optional(z.enum([
        'id',
        'name',
        'resource',
        'created_at'
    ]))
}));

export const zProductRoleSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zProductRoleFilter),
    sort_by: z.optional(z.enum([
        'id',
        'name',
        'created_at'
    ]))
}));

export const zProductApiKeySearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zProductApiKeyFilter),
    sort_by: z.optional(z.enum([
        'id',
        'name',
        'created_at',
        'last_used_at',
        'status'
    ]))
}));

export const zOrganizationApiKeySearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zOrganizationApiKeyFilter),
    sort_by: z.optional(z.enum([
        'id',
        'name',
        'created_at',
        'last_used_at',
        'status'
    ]))
}));

export const zProductApiKeyUpdateRequest = z.object({
    name: z.optional(z.string().min(2).max(100)),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    permissions: z.optional(z.array(z.string()))
});

export const zOrganizationApiKeyUpdateRequest = z.object({
    name: z.optional(z.string().min(2).max(100)),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    status: z.optional(zOrganizationApiKeyStatus)
});

export const zOrganizationApiKeyValidateRequest = z.object({
    api_key: z.string(),
    required_scopes: z.array(z.string())
});

export const zOrganizationApiKeyValidateResponse = z.object({
    api_key: zOrganizationApiKeyResponse,
    permissions: z.array(z.string()),
    missing_privileges: z.array(z.string())
});

export const zOrganizationApiKeyValidateForbiddenResponse = z.object({
    api_key: zOrganizationApiKeyResponse,
    permissions: z.array(z.string()),
    missing_privileges: z.array(z.string())
});

export const zUserResponse = z.object({
    email: z.email(),
    id: z.string(),
    role: z.string()
});

export const zFoundingMemberRequest = z.object({
    product_user_id: zKsuid,
    role_id: zKsuid
});

export const zProductOrganizationRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ])),
    metadata: z.optional(zMetadata),
    founding_member: z.optional(zFoundingMemberRequest)
});

export const zProductOrganizationResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    metadata: z.optional(zMetadata),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductOrganizationSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zOrganizationFilter),
    sort_by: z.optional(z.enum([
        'name',
        'created_at',
        'updated_at'
    ]))
}));

export const zProductOrganizationListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductOrganizationResponse)
}));

export const zProductWorkspaceRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.optional(z.union([
        z.string().max(500),
        z.null()
    ]))
});

export const zProductWorkspaceResponse = z.object({
    id: zKsuid,
    organization_id: zKsuid,
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zProductWorkspaceSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zWorkspaceFilter),
    sort_by: z.optional(z.enum([
        'name',
        'created_at',
        'updated_at'
    ]))
}));

export const zProductWorkspaceListResponse = zPagedListResponse.and(z.object({
    items: z.array(zProductWorkspaceResponse)
}));

/**
 * Represents a member of an organization with their role details.
 */
export const zOrganizationMemberResponse = z.object({
    product_user_id: zKsuid,
    email: z.email(),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    external_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    role: z.object({
        id: zKsuid,
        name: z.string(),
        permissions: z.optional(z.array(z.string()))
    }),
    joined_at: z.iso.datetime()
});

/**
 * Paginated list of organization members.
 */
export const zOrganizationMemberListResponse = zPagedListResponse.and(z.object({
    items: z.array(zOrganizationMemberResponse)
}));

/**
 * Request body for adding a member to an organization.
 */
export const zOrganizationMemberRequest = z.object({
    product_user_id: zKsuid,
    role_id: zKsuid
});

/**
 * Request body for updating a member's role within an organization.
 */
export const zOrganizationMemberRoleRequest = z.object({
    role_id: zKsuid
});

/**
 * Filter criteria for searching organization members.
 */
export const zOrganizationMemberFilter = z.object({
    product_user_ids: z.optional(z.array(zKsuid)),
    external_ids: z.optional(z.array(z.string())),
    emails: z.optional(z.array(z.email())),
    role_ids: z.optional(z.array(zKsuid))
});

export const zOrganizationMemberSearchRequest = zSearchRequest.and(z.object({
    filter: z.optional(zOrganizationMemberFilter),
    sort_by: z.optional(z.enum([
        'joined_at',
        'email'
    ]))
}));

/**
 * Additional fields to include in organization member responses.
 */
export const zOrganizationMemberInclude = z.enum([
    'role_permissions'
]);

/**
 * The type of integration provider.
 */
export const zIntegrationProviderType = z.enum([
    'CLERK',
    'SMTP'
]);

/**
 * The status of the integration instance.
 */
export const zIntegrationInstanceStatus = z.enum([
    'ACTIVE',
    'INACTIVE',
    'CONFIGURING',
    'ERROR'
]);

/**
 * The processing status of an integration event.
 */
export const zIntegrationEventStatus = z.enum([
    'PENDING',
    'PROCESSING',
    'PROCESSED',
    'FAILED'
]);

/**
 * Provider-specific configuration for Clerk integration.
 */
export const zClerkIntegrationConfig = z.object({
    api_key: z.optional(z.string()),
    issue_reason: z.optional(z.union([
        z.string().max(500),
        z.null()
    ]))
});

/**
 * Provider-specific configuration for SMTP email integration.
 */
export const zSmtpIntegrationConfig = z.object({
    host: z.optional(z.string()),
    port: z.optional(z.int()).default(587),
    encryption: z.optional(z.enum([
        'STARTTLS',
        'TLS',
        'NONE'
    ])),
    auth_method: z.optional(z.enum([
        'PLAIN',
        'LOGIN'
    ])),
    username: z.optional(z.string()),
    password: z.optional(z.string()),
    from_address: z.optional(z.string()),
    from_name: z.optional(z.string()),
    reply_to: z.optional(z.string())
});

/**
 * Provider-specific configuration payload.
 */
export const zIntegrationProviderConfig = z.union([
    zClerkIntegrationConfig,
    zSmtpIntegrationConfig
]);

/**
 * Non-sensitive SMTP configuration fields returned in API responses. Password is never included.
 */
export const zSmtpIntegrationPublicConfig = z.object({
    host: z.optional(z.string()),
    port: z.optional(z.int()).default(587),
    encryption: z.optional(z.enum([
        'STARTTLS',
        'TLS',
        'NONE'
    ])),
    auth_method: z.optional(z.enum([
        'PLAIN',
        'LOGIN'
    ])),
    username: z.optional(z.string()),
    from_address: z.optional(z.string()),
    from_name: z.optional(z.string()),
    reply_to: z.optional(z.string())
});

/**
 * Non-sensitive provider configuration returned in API responses.
 */
export const zIntegrationProviderPublicConfig = zSmtpIntegrationPublicConfig;

export const zSmtpIntegrationInstanceCreateRequest = z.object({
    provider_type: z.enum([
        'SMTP'
    ]),
    config: zSmtpIntegrationConfig
});

export const zClerkIntegrationInstanceCreateRequest = z.object({
    provider_type: z.enum([
        'CLERK'
    ]),
    config: z.optional(zClerkIntegrationConfig)
});

/**
 * Create request for a provider integration instance.
 */
export const zIntegrationInstanceCreateRequest = z.union([
    z.object({
        provider_type: z.literal('CLERK')
    }).and(zClerkIntegrationInstanceCreateRequest),
    z.object({
        provider_type: z.literal('SMTP')
    }).and(zSmtpIntegrationInstanceCreateRequest)
]);

export const zIntegrationInstanceUpdateRequest = z.object({
    is_enabled: z.optional(z.boolean()),
    webhook_secret: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    config: z.optional(zIntegrationProviderConfig)
});

export const zIntegrationInstanceResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    provider_type: zIntegrationProviderType,
    config_version: z.int(),
    is_enabled: z.boolean(),
    status: zIntegrationInstanceStatus,
    last_error: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    webhook_secret_obfuscated: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    public_config: z.optional(zIntegrationProviderPublicConfig)
});

export const zIntegrationInstanceListResponse = z.object({
    items: z.array(zIntegrationInstanceResponse),
    count: z.int()
});

export const zIntegrationWebhookResponse = z.object({
    event_id: zKsuid,
    status: zIntegrationEventStatus
});

/**
 * Severity level for integration audit events.
 */
export const zIntegrationAuditLogSeverity = z.enum([
    'INFO',
    'SUCCESS',
    'WARNING',
    'ERROR'
]);

export const zIntegrationAuditLogEntryResponse = z.object({
    id: zKsuid,
    integration_instance_id: zKsuid,
    action: z.string(),
    severity: zIntegrationAuditLogSeverity,
    message: z.string(),
    metadata: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

export const zIntegrationAuditLogListResponse = z.object({
    items: z.array(zIntegrationAuditLogEntryResponse),
    count: z.int()
});

export const zEmailVariableType = z.enum([
    'STRING',
    'NUMBER',
    'BOOL',
    'LIST',
    'OBJECT'
]);

export const zEmailVariableSchemaProperty = z.object({
    name: z.string(),
    type: zEmailVariableType
});

export const zEmailVariableSchemaItems = z.object({
    type: zEmailVariableType,
    properties: z.optional(z.array(zEmailVariableSchemaProperty))
});

export const zEmailVariableSchema = z.object({
    name: z.string(),
    type: zEmailVariableType,
    required: z.optional(z.boolean()).default(false),
    help: z.optional(z.string()),
    items: z.optional(zEmailVariableSchemaItems),
    properties: z.optional(z.array(zEmailVariableSchemaProperty))
});

export const zEmailTemplateVersionStatus = z.enum([
    'DRAFT',
    'PUBLISHED',
    'ARCHIVED'
]);

export const zEmailSendStatus = z.enum([
    'QUEUED',
    'SENDING',
    'SENT',
    'FAILED'
]);

export const zEmailTemplateCreateRequest = z.object({
    slug: z.string().max(120),
    name: z.string(),
    description: z.optional(z.string()),
    subject: z.string(),
    body_html: z.string(),
    body_text: z.optional(z.string()),
    variables: z.optional(z.array(zEmailVariableSchema))
});

export const zEmailTemplateUpdateRequest = z.object({
    name: z.optional(z.string()),
    description: z.optional(z.string()),
    is_active: z.optional(z.boolean())
});

export const zEmailTemplateDraftUpdateRequest = z.object({
    subject: z.optional(z.string()),
    body_html: z.optional(z.string()),
    body_text: z.optional(z.string()),
    variables: z.optional(z.array(zEmailVariableSchema))
});

export const zEmailTemplateResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    slug: z.string(),
    name: z.string(),
    description: z.optional(z.string()),
    draft_version_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    published_version_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.boolean(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zEmailTemplateVersionResponse = z.object({
    id: zKsuid,
    template_id: zKsuid,
    version_number: z.int(),
    subject: z.string(),
    body_html: z.string(),
    body_text: z.optional(z.string()),
    variables: z.optional(z.array(zEmailVariableSchema)),
    status: zEmailTemplateVersionStatus,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    published_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

export const zEmailTemplateListResponse = z.object({
    items: z.array(zEmailTemplateResponse),
    count: z.int()
});

export const zTemplateExample = z.object({
    id: z.string(),
    name: z.string(),
    variables: z.record(z.string(), z.unknown())
});

export const zTemplateExampleListRequest = z.object({
    examples: z.array(zTemplateExample)
});

export const zTemplateExampleListResponse = z.object({
    examples: z.array(zTemplateExample)
});

export const zEmailTemplatePreviewRequest = z.object({
    variables: z.optional(z.record(z.string(), z.unknown())),
    use_published: z.optional(z.boolean()).default(false)
});

export const zEmailTemplatePreviewResponse = z.object({
    subject: z.string(),
    body_html: z.string(),
    body_text: z.string(),
    warnings: z.array(z.string())
});

export const zEmailSendRequest = z.object({
    template_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    template_slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    to_address: z.email(),
    to_name: z.optional(z.string()),
    variables: z.optional(z.record(z.string(), z.unknown())),
    dedupe_key: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    use_draft: z.optional(z.boolean()).default(false)
});

export const zEmailSendRecordResponse = z.object({
    id: zKsuid,
    product_id: zKsuid,
    integration_instance_id: z.optional(z.string()),
    template_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    template_version_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dedupe_key: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    to_address: z.string(),
    to_name: z.optional(z.string()),
    from_address: z.string(),
    from_name: z.optional(z.string()),
    subject: z.string(),
    status: zEmailSendStatus,
    attempts: z.int(),
    last_error: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sent_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

export const zEmailSendRecordListResponse = z.object({
    items: z.array(zEmailSendRecordResponse),
    count: z.int()
});

/**
 * The KSUID of the platform invitation.
 */
export const zPlatformInvitationIdParameter = zKsuid;

/**
 * The KSUID of the platform invitation.
 */
export const zPlatformUserIdParameter = zKsuid;

/**
 * The KSUID of the product.
 */
export const zProductIdParameter = zKsuid;

/**
 * The KSUID of the organization.
 */
export const zOrganizationIdParameter = zKsuid;

/**
 * The KSUID of the workspace.
 */
export const zWorkspaceIdParameter = zKsuid;

/**
 * The KSUID of the product Product User.
 */
export const zProductUserIdParameter = zKsuid;

/**
 * The KSUID of the product role.
 */
export const zProductRoleIdParameter = zKsuid;

/**
 * The resource permission name (e.g., file:read, document:edit).
 */
export const zResourcePermissionNameParameter = z.string().min(2).max(200);

/**
 * permission name
 */
export const zProductPermissionIdParameter = z.string();

/**
 * The KSUID of the product API key.
 */
export const zProductApiKeyIdParameter = zKsuid;

/**
 * The KSUID of the organization API key.
 */
export const zOrganizationApiKeyIdParameter = zKsuid;

/**
 * The KSUID of the integration instance.
 */
export const zIntegrationInstanceIdParameter = zKsuid;

/**
 * The integration provider type (e.g., CLERK).
 */
export const zProviderTypeParameter = zIntegrationProviderType;

/**
 * The KSUID of the email template.
 */
export const zEmailTemplateIdParameter = zKsuid;

export const zLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successfully logged out.
 * The refresh token cookie is removed.
 *
 */
export const zLogoutResponse = z.void();

export const zLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zLoginResponse = zAuthTokenResponse;

export const zRefreshTokenData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zRefreshTokenResponse = zAuthTokenResponse;

export const zRegisterData = z.object({
    body: zRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zRegisterResponse = zAuthTokenResponse;

export const zGetCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetCurrentUserResponse = zUserResponse;

export const zCreateProductData = z.object({
    body: zProductRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Product created successfully.
 */
export const zCreateProductResponse = zProductResponse;

export const zSearchProductsData = z.object({
    body: zProductSearchRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * List of matching products.
 */
export const zSearchProductsResponse = zProductListResponse;

export const zDeleteProductData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product deleted successfully.
 */
export const zDeleteProductResponse = z.void();

export const zGetProductData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product details.
 */
export const zGetProductResponse = zProductResponse;

export const zUpdateProductData = z.object({
    body: zProductRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product updated successfully.
 */
export const zUpdateProductResponse = zProductResponse;

export const zListIntegrationInstancesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * List of integration instances.
 */
export const zListIntegrationInstancesResponse = zIntegrationInstanceListResponse;

export const zCreateIntegrationInstanceData = z.object({
    body: zIntegrationInstanceCreateRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Integration instance created successfully.
 */
export const zCreateIntegrationInstanceResponse = zIntegrationInstanceResponse;

export const zDeleteIntegrationInstanceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        integration_instance_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Integration instance deleted successfully.
 */
export const zDeleteIntegrationInstanceResponse = z.void();

export const zGetIntegrationInstanceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        integration_instance_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Integration instance details.
 */
export const zGetIntegrationInstanceResponse = zIntegrationInstanceResponse;

export const zUpdateIntegrationInstanceData = z.object({
    body: zIntegrationInstanceUpdateRequest,
    path: z.object({
        product_id: zKsuid,
        integration_instance_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Integration instance updated successfully.
 */
export const zUpdateIntegrationInstanceResponse = zIntegrationInstanceResponse;

export const zListIntegrationAuditLogsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        integration_instance_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * List of audit log entries for the integration instance.
 */
export const zListIntegrationAuditLogsResponse = zIntegrationAuditLogListResponse;

export const zIngestWebhookData = z.object({
    body: z.record(z.string(), z.unknown()),
    path: z.object({
        product_id: zKsuid,
        provider_type: zIntegrationProviderType
    }),
    query: z.optional(z.never())
});

/**
 * Webhook processed successfully.
 */
export const zIngestWebhookResponse = zIntegrationWebhookResponse;

export const zCreateProductResourcePermissionData = z.object({
    body: zCreateProductResourcePermissionRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Resource permission created successfully.
 */
export const zCreateProductResourcePermissionResponse = zProductResourcePermissionResponse;

export const zSearchProductResourcePermissionsData = z.object({
    body: zProductResourcePermissionSearchRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * List of matching resource permissions.
 */
export const zSearchProductResourcePermissionsResponse = zProductResourcePermissionListResponse;

export const zDeleteProductResourcePermissionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        permission_name: z.string().min(2).max(200)
    }),
    query: z.optional(z.never())
});

/**
 * Resource permission deleted successfully.
 */
export const zDeleteProductResourcePermissionResponse = z.void();

export const zGetProductResourcePermissionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        permission_name: z.string().min(2).max(200)
    }),
    query: z.optional(z.never())
});

/**
 * Resource permission details.
 */
export const zGetProductResourcePermissionResponse = zProductResourcePermissionResponse;

export const zUpdateProductResourcePermissionData = z.object({
    body: zUpdateProductResourcePermissionRequest,
    path: z.object({
        product_id: zKsuid,
        permission_name: z.string().min(2).max(200)
    }),
    query: z.optional(z.never())
});

/**
 * Resource permission updated successfully.
 */
export const zUpdateProductResourcePermissionResponse = zProductResourcePermissionResponse;

export const zCreatePlatformInvitationData = z.object({
    body: zPlatformInvitationRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Platform Invitation created successfully. Includes the invitation code.
 */
export const zCreatePlatformInvitationResponse = zPlatformInvitationResponse;

export const zSearchPlatformInvitationsData = z.object({
    body: zPlatformInvitationSearchRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A list of platform invitations.
 */
export const zSearchPlatformInvitationsResponse = zPlatformInvitationListResponse;

export const zDeletePlatformInvitationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        invitation_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Platform Invitation deleted successfully, or invitation did not exist (idempotent operation).
 */
export const zDeletePlatformInvitationResponse = z.void();

export const zGetPlatformInvitationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        invitation_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Platform Invitation details.
 */
export const zGetPlatformInvitationResponse = zPlatformInvitationResponse;

export const zSearchPlatformUsersData = z.object({
    body: zPlatformUserSearchRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A list of platform Users.
 */
export const zSearchPlatformUsersResponse = zPlatformUserListResponse;

export const zDeletePlatformUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        platform_user_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Platform User deleted successfully, or User did not exist (idempotent operation).
 */
export const zDeletePlatformUserResponse = z.void();

export const zGetPlatformUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        platform_user_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Platform User details.
 */
export const zGetPlatformUserResponse = zPlatformUserResponse;

export const zSearchProductPermissionsData = z.object({
    body: zProductPermissionSearchRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of built-in product permissions.
 */
export const zSearchProductPermissionsResponse = zProductPermissionListResponse;

export const zGetProductPermissionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        permission_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Built-in product permission details.
 */
export const zGetProductPermissionResponse = zProductPermissionResponse;

export const zSearchProductRolesData = z.object({
    body: zProductRoleSearchRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of product roles.
 */
export const zSearchProductRolesResponse = zProductRoleListResponse;

export const zCreateProductRoleData = z.object({
    body: zProductRoleCreateRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Application role created successfully.
 */
export const zCreateProductRoleResponse = zProductRoleResponse;

export const zDeleteProductRoleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        role_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Application role deleted successfully.
 */
export const zDeleteProductRoleResponse = z.void();

export const zGetProductRoleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        role_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product role details.
 */
export const zGetProductRoleResponse = zProductRoleResponse;

export const zUpdateProductRoleData = z.object({
    body: zProductRoleUpdateRequest,
    path: z.object({
        product_id: zKsuid,
        role_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Application role updated successfully.
 */
export const zUpdateProductRoleResponse = zProductRoleResponse;

export const zAssignPermissionToProductRoleData = z.object({
    body: zAssignPermissionRequest,
    path: z.object({
        product_id: zKsuid,
        role_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Permission assigned successfully.
 */
export const zAssignPermissionToProductRoleResponse = z.void();

export const zUnassignPermissionFromProductRoleData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        role_id: zKsuid,
        permission_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Permission unassigned successfully.
 */
export const zUnassignPermissionFromProductRoleResponse = z.void();

export const zSearchProductApiKeysData = z.object({
    body: zProductApiKeySearchRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of product API keys.
 */
export const zSearchProductApiKeysResponse = zProductApiKeyListResponse;

export const zCreateProductApiKeyData = z.object({
    body: zProductApiKeyCreateRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product API key created successfully.
 */
export const zCreateProductApiKeyResponse = zCreatedProductApiKeyResponse;

export const zDeleteProductApiKeyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        api_key_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product API key deleted successfully.
 */
export const zDeleteProductApiKeyResponse = z.void();

export const zGetProductApiKeyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        api_key_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product API key details.
 */
export const zGetProductApiKeyResponse = zProductApiKeyResponse;

export const zUpdateProductApiKeyData = z.object({
    body: zProductApiKeyUpdateRequest,
    path: z.object({
        product_id: zKsuid,
        api_key_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product API key updated successfully.
 */
export const zUpdateProductApiKeyResponse = zProductApiKeyResponse;

export const zCreateProductUserData = z.object({
    body: z.object({
        email: z.email(),
        name: z.optional(z.union([
            z.string().min(1).max(100),
            z.null()
        ])),
        status: z.optional(zProductUserStatus)
    }),
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product user created successfully.
 */
export const zCreateProductUserResponse = zProductUserResponse;

export const zSearchProductUsersData = z.object({
    body: zProductUserSearchRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of product users for the product.
 */
export const zSearchProductUsersResponse = zProductUserListResponse;

export const zDeleteProductUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        product_user_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product user deleted successfully.
 */
export const zDeleteProductUserResponse = z.void();

export const zGetProductUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        product_user_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product Product User details.
 */
export const zGetProductUserResponse = zProductUserResponse;

export const zListUserOrganizationsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        product_user_id: zKsuid
    }),
    query: z.optional(z.object({
        include: z.optional(z.array(zUserOrganizationInclude))
    }))
});

/**
 * List of organizations the user belongs to.
 */
export const zListUserOrganizationsResponse = zUserOrganizationListResponse;

export const zGetUserOrganizationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        product_user_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.object({
        include: z.optional(z.array(zUserOrganizationInclude))
    }))
});

/**
 * Organization details from the user's perspective.
 */
export const zGetUserOrganizationResponse = zUserOrganizationResponse;

export const zSearchOrganizationApiKeysData = z.object({
    body: zOrganizationApiKeySearchRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of organization API keys.
 */
export const zSearchOrganizationApiKeysResponse = zOrganizationApiKeyListResponse;

export const zCreateOrganizationApiKeyData = z.object({
    body: zOrganizationApiKeyCreateRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Organization API key created successfully.
 */
export const zCreateOrganizationApiKeyResponse = zCreatedOrganizationApiKeyResponse;

export const zDeleteOrganizationApiKeyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        api_key_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Organization API key deleted successfully.
 */
export const zDeleteOrganizationApiKeyResponse = z.void();

export const zGetOrganizationApiKeyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        api_key_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Organization API key details.
 */
export const zGetOrganizationApiKeyResponse = zOrganizationApiKeyResponse;

export const zUpdateOrganizationApiKeyData = z.object({
    body: zOrganizationApiKeyUpdateRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        api_key_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Organization API key updated successfully.
 */
export const zUpdateOrganizationApiKeyResponse = zOrganizationApiKeyResponse;

export const zValidateOrganizationApiKeyData = z.object({
    body: zOrganizationApiKeyValidateRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Organization API key validation result.
 */
export const zValidateOrganizationApiKeyResponse = zOrganizationApiKeyValidateResponse;

export const zCreateProductOrganizationData = z.object({
    body: zProductOrganizationRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product organization created successfully.
 */
export const zCreateProductOrganizationResponse = zProductOrganizationResponse;

export const zSearchProductOrganizationsData = z.object({
    body: zProductOrganizationSearchRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of product organizations for the product.
 */
export const zSearchProductOrganizationsResponse = zProductOrganizationListResponse;

export const zUpdateProductOrganizationData = z.object({
    body: zProductOrganizationRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Product organization updated successfully.
 */
export const zUpdateProductOrganizationResponse = zProductOrganizationResponse;

export const zCreateOrganizationWorkspaceData = z.object({
    body: zProductWorkspaceRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Workspace created successfully.
 */
export const zCreateOrganizationWorkspaceResponse = zProductWorkspaceResponse;

export const zSearchOrganizationWorkspacesData = z.object({
    body: zProductWorkspaceSearchRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * A list of workspaces for the organization.
 */
export const zSearchOrganizationWorkspacesResponse = zProductWorkspaceListResponse;

export const zDeleteOrganizationWorkspaceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        workspace_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Workspace deleted successfully.
 */
export const zDeleteOrganizationWorkspaceResponse = z.void();

export const zGetOrganizationWorkspaceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        workspace_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Workspace details.
 */
export const zGetOrganizationWorkspaceResponse = zProductWorkspaceResponse;

export const zUpdateOrganizationWorkspaceData = z.object({
    body: zProductWorkspaceRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        workspace_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Workspace updated successfully.
 */
export const zUpdateOrganizationWorkspaceResponse = zProductWorkspaceResponse;

export const zAddOrganizationMemberData = z.object({
    body: zOrganizationMemberRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Member successfully added
 */
export const zAddOrganizationMemberResponse = zOrganizationMemberResponse;

export const zRemoveOrganizationMemberData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        product_user_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Successfully removed
 */
export const zRemoveOrganizationMemberResponse = z.void();

export const zGetOrganizationMemberData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        product_user_id: zKsuid
    }),
    query: z.optional(z.object({
        include: z.optional(zOrganizationMemberInclude)
    }))
});

/**
 * Success
 */
export const zGetOrganizationMemberResponse = zOrganizationMemberResponse;

export const zUpdateOrganizationMemberRoleData = z.object({
    body: zOrganizationMemberRoleRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid,
        product_user_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateOrganizationMemberRoleResponse = zOrganizationMemberResponse;

export const zSearchOrganizationMembersData = z.object({
    body: zOrganizationMemberSearchRequest,
    path: z.object({
        product_id: zKsuid,
        organization_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zSearchOrganizationMembersResponse = zOrganizationMemberListResponse;

export const zListEmailTemplatesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.object({
        limit: z.optional(z.coerce.bigint()).default(BigInt(50)),
        offset: z.optional(z.coerce.bigint()).default(BigInt(0))
    }))
});

/**
 * Success
 */
export const zListEmailTemplatesResponse = zEmailTemplateListResponse;

export const zCreateEmailTemplateData = z.object({
    body: zEmailTemplateCreateRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateEmailTemplateResponse = zEmailTemplateResponse;

export const zDeleteEmailTemplateData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Deleted
 */
export const zDeleteEmailTemplateResponse = z.void();

export const zGetEmailTemplateData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetEmailTemplateResponse = zEmailTemplateResponse;

export const zUpdateEmailTemplateData = z.object({
    body: zEmailTemplateUpdateRequest,
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateEmailTemplateResponse = zEmailTemplateResponse;

export const zGetEmailTemplateDraftData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetEmailTemplateDraftResponse = zEmailTemplateVersionResponse;

export const zUpdateEmailTemplateDraftData = z.object({
    body: zEmailTemplateDraftUpdateRequest,
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateEmailTemplateDraftResponse = zEmailTemplateVersionResponse;

export const zPublishEmailTemplateData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Published version
 */
export const zPublishEmailTemplateResponse = zEmailTemplateVersionResponse;

export const zPreviewEmailTemplateData = z.object({
    body: zEmailTemplatePreviewRequest,
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Rendered preview
 */
export const zPreviewEmailTemplateResponse = zEmailTemplatePreviewResponse;

export const zGetEmailTemplateExamplesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Example list
 */
export const zGetEmailTemplateExamplesResponse = zTemplateExampleListResponse;

export const zSaveEmailTemplateExamplesData = z.object({
    body: zTemplateExampleListRequest,
    path: z.object({
        product_id: zKsuid,
        email_template_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Updated example list
 */
export const zSaveEmailTemplateExamplesResponse = zTemplateExampleListResponse;

export const zListEmailSendsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.object({
        template_id: z.optional(z.string()),
        status: z.optional(zEmailSendStatus),
        limit: z.optional(z.coerce.bigint()).default(BigInt(50)),
        offset: z.optional(z.coerce.bigint()).default(BigInt(0))
    }))
});

/**
 * Success
 */
export const zListEmailSendsResponse = zEmailSendRecordListResponse;

export const zSendEmailData = z.object({
    body: zEmailSendRequest,
    path: z.object({
        product_id: zKsuid
    }),
    query: z.optional(z.never())
});

/**
 * Send record created
 */
export const zSendEmailResponse = zEmailSendRecordResponse;
