/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsUserImport } from './routes/settings/user'
import { Route as SettingsAppImport } from './routes/settings/app'
import { Route as ProductsProductsImport } from './routes/products/products'
import { Route as ProductsProductUsersImport } from './routes/products/product-users'
import { Route as ProductsProductRolesRouteImport } from './routes/products/product-roles-route'
import { Route as ProductsProductResourcePermissionsImport } from './routes/products/product-resource-permissions'
import { Route as ProductsProductApiKeysImport } from './routes/products/product-api-keys'
import { Route as ProductsPermissionsImport } from './routes/products/permissions'
import { Route as ProductsEmailTemplatesImport } from './routes/products/email-templates'
import { Route as ProductsEmailTemplateBuilderImport } from './routes/products/email-template-builder'
import { Route as ProductsEmailSendsImport } from './routes/products/email-sends'
import { Route as PlatformRegisterImport } from './routes/platform/register'
import { Route as PlatformPlatformUsersImport } from './routes/platform/platform-users'
import { Route as PlatformLoginImport } from './routes/platform/login'
import { Route as PlatformInvitationsImport } from './routes/platform/invitations'
import { Route as PlatformIntegrationsImport } from './routes/platform/integrations'
import { Route as PlatformIntegrationClerkImport } from './routes/platform/integration-clerk'
import { Route as PlatformInitImport } from './routes/platform/init'
import { Route as OrganizationsWorkspacesImport } from './routes/organizations/workspaces'
import { Route as OrganizationsWorkspaceMembershipsImport } from './routes/organizations/workspace-memberships'
import { Route as OrganizationsOrganizationsImport } from './routes/organizations/organizations'
import { Route as OrganizationsOrganizationMembershipsImport } from './routes/organizations/organization-memberships'
import { Route as OrganizationsOrganizationApiKeysImport } from './routes/organizations/organization-api-keys'
import { Route as ProductsProductIdEditImport } from './routes/products/$productId.edit'
import { Route as PlatformProductIdIntegrationsImport } from './routes/platform/$productId.integrations'
import { Route as PlatformProductIdIntegrationSmtpImport } from './routes/platform/$productId.integration-smtp'
import { Route as PlatformProductIdIntegrationClerkImport } from './routes/platform/$productId.integration-clerk'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsUserRoute = SettingsUserImport.update({
  id: '/settings/user',
  path: '/settings/user',
  getParentRoute: () => rootRoute,
} as any)

const SettingsAppRoute = SettingsAppImport.update({
  id: '/settings/app',
  path: '/settings/app',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductsRoute = ProductsProductsImport.update({
  id: '/products/products',
  path: '/products/products',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductUsersRoute = ProductsProductUsersImport.update({
  id: '/products/product-users',
  path: '/products/product-users',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductRolesRouteRoute = ProductsProductRolesRouteImport.update({
  id: '/products/product-roles-route',
  path: '/products/product-roles-route',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductResourcePermissionsRoute =
  ProductsProductResourcePermissionsImport.update({
    id: '/products/product-resource-permissions',
    path: '/products/product-resource-permissions',
    getParentRoute: () => rootRoute,
  } as any)

const ProductsProductApiKeysRoute = ProductsProductApiKeysImport.update({
  id: '/products/product-api-keys',
  path: '/products/product-api-keys',
  getParentRoute: () => rootRoute,
} as any)

const ProductsPermissionsRoute = ProductsPermissionsImport.update({
  id: '/products/permissions',
  path: '/products/permissions',
  getParentRoute: () => rootRoute,
} as any)

const ProductsEmailTemplatesRoute = ProductsEmailTemplatesImport.update({
  id: '/products/email-templates',
  path: '/products/email-templates',
  getParentRoute: () => rootRoute,
} as any)

const ProductsEmailTemplateBuilderRoute =
  ProductsEmailTemplateBuilderImport.update({
    id: '/products/email-template-builder',
    path: '/products/email-template-builder',
    getParentRoute: () => rootRoute,
  } as any)

const ProductsEmailSendsRoute = ProductsEmailSendsImport.update({
  id: '/products/email-sends',
  path: '/products/email-sends',
  getParentRoute: () => rootRoute,
} as any)

const PlatformRegisterRoute = PlatformRegisterImport.update({
  id: '/platform/register',
  path: '/platform/register',
  getParentRoute: () => rootRoute,
} as any)

const PlatformPlatformUsersRoute = PlatformPlatformUsersImport.update({
  id: '/platform/platform-users',
  path: '/platform/platform-users',
  getParentRoute: () => rootRoute,
} as any)

const PlatformLoginRoute = PlatformLoginImport.update({
  id: '/platform/login',
  path: '/platform/login',
  getParentRoute: () => rootRoute,
} as any)

const PlatformInvitationsRoute = PlatformInvitationsImport.update({
  id: '/platform/invitations',
  path: '/platform/invitations',
  getParentRoute: () => rootRoute,
} as any)

const PlatformIntegrationsRoute = PlatformIntegrationsImport.update({
  id: '/platform/integrations',
  path: '/platform/integrations',
  getParentRoute: () => rootRoute,
} as any)

const PlatformIntegrationClerkRoute = PlatformIntegrationClerkImport.update({
  id: '/platform/integration-clerk',
  path: '/platform/integration-clerk',
  getParentRoute: () => rootRoute,
} as any)

const PlatformInitRoute = PlatformInitImport.update({
  id: '/platform/init',
  path: '/platform/init',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsWorkspacesRoute = OrganizationsWorkspacesImport.update({
  id: '/organizations/workspaces',
  path: '/organizations/workspaces',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsWorkspaceMembershipsRoute =
  OrganizationsWorkspaceMembershipsImport.update({
    id: '/organizations/workspace-memberships',
    path: '/organizations/workspace-memberships',
    getParentRoute: () => rootRoute,
  } as any)

const OrganizationsOrganizationsRoute = OrganizationsOrganizationsImport.update(
  {
    id: '/organizations/organizations',
    path: '/organizations/organizations',
    getParentRoute: () => rootRoute,
  } as any,
)

const OrganizationsOrganizationMembershipsRoute =
  OrganizationsOrganizationMembershipsImport.update({
    id: '/organizations/organization-memberships',
    path: '/organizations/organization-memberships',
    getParentRoute: () => rootRoute,
  } as any)

const OrganizationsOrganizationApiKeysRoute =
  OrganizationsOrganizationApiKeysImport.update({
    id: '/organizations/organization-api-keys',
    path: '/organizations/organization-api-keys',
    getParentRoute: () => rootRoute,
  } as any)

const ProductsProductIdEditRoute = ProductsProductIdEditImport.update({
  id: '/products/$productId/edit',
  path: '/products/$productId/edit',
  getParentRoute: () => rootRoute,
} as any)

const PlatformProductIdIntegrationsRoute =
  PlatformProductIdIntegrationsImport.update({
    id: '/platform/$productId/integrations',
    path: '/platform/$productId/integrations',
    getParentRoute: () => rootRoute,
  } as any)

const PlatformProductIdIntegrationSmtpRoute =
  PlatformProductIdIntegrationSmtpImport.update({
    id: '/platform/$productId/integration-smtp',
    path: '/platform/$productId/integration-smtp',
    getParentRoute: () => rootRoute,
  } as any)

const PlatformProductIdIntegrationClerkRoute =
  PlatformProductIdIntegrationClerkImport.update({
    id: '/platform/$productId/integration-clerk',
    path: '/platform/$productId/integration-clerk',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/organizations/organization-api-keys': {
      id: '/organizations/organization-api-keys'
      path: '/organizations/organization-api-keys'
      fullPath: '/organizations/organization-api-keys'
      preLoaderRoute: typeof OrganizationsOrganizationApiKeysImport
      parentRoute: typeof rootRoute
    }
    '/organizations/organization-memberships': {
      id: '/organizations/organization-memberships'
      path: '/organizations/organization-memberships'
      fullPath: '/organizations/organization-memberships'
      preLoaderRoute: typeof OrganizationsOrganizationMembershipsImport
      parentRoute: typeof rootRoute
    }
    '/organizations/organizations': {
      id: '/organizations/organizations'
      path: '/organizations/organizations'
      fullPath: '/organizations/organizations'
      preLoaderRoute: typeof OrganizationsOrganizationsImport
      parentRoute: typeof rootRoute
    }
    '/organizations/workspace-memberships': {
      id: '/organizations/workspace-memberships'
      path: '/organizations/workspace-memberships'
      fullPath: '/organizations/workspace-memberships'
      preLoaderRoute: typeof OrganizationsWorkspaceMembershipsImport
      parentRoute: typeof rootRoute
    }
    '/organizations/workspaces': {
      id: '/organizations/workspaces'
      path: '/organizations/workspaces'
      fullPath: '/organizations/workspaces'
      preLoaderRoute: typeof OrganizationsWorkspacesImport
      parentRoute: typeof rootRoute
    }
    '/platform/init': {
      id: '/platform/init'
      path: '/platform/init'
      fullPath: '/platform/init'
      preLoaderRoute: typeof PlatformInitImport
      parentRoute: typeof rootRoute
    }
    '/platform/integration-clerk': {
      id: '/platform/integration-clerk'
      path: '/platform/integration-clerk'
      fullPath: '/platform/integration-clerk'
      preLoaderRoute: typeof PlatformIntegrationClerkImport
      parentRoute: typeof rootRoute
    }
    '/platform/integrations': {
      id: '/platform/integrations'
      path: '/platform/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof PlatformIntegrationsImport
      parentRoute: typeof rootRoute
    }
    '/platform/invitations': {
      id: '/platform/invitations'
      path: '/platform/invitations'
      fullPath: '/platform/invitations'
      preLoaderRoute: typeof PlatformInvitationsImport
      parentRoute: typeof rootRoute
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginImport
      parentRoute: typeof rootRoute
    }
    '/platform/platform-users': {
      id: '/platform/platform-users'
      path: '/platform/platform-users'
      fullPath: '/platform/platform-users'
      preLoaderRoute: typeof PlatformPlatformUsersImport
      parentRoute: typeof rootRoute
    }
    '/platform/register': {
      id: '/platform/register'
      path: '/platform/register'
      fullPath: '/platform/register'
      preLoaderRoute: typeof PlatformRegisterImport
      parentRoute: typeof rootRoute
    }
    '/products/email-sends': {
      id: '/products/email-sends'
      path: '/products/email-sends'
      fullPath: '/products/email-sends'
      preLoaderRoute: typeof ProductsEmailSendsImport
      parentRoute: typeof rootRoute
    }
    '/products/email-template-builder': {
      id: '/products/email-template-builder'
      path: '/products/email-template-builder'
      fullPath: '/products/email-template-builder'
      preLoaderRoute: typeof ProductsEmailTemplateBuilderImport
      parentRoute: typeof rootRoute
    }
    '/products/email-templates': {
      id: '/products/email-templates'
      path: '/products/email-templates'
      fullPath: '/products/email-templates'
      preLoaderRoute: typeof ProductsEmailTemplatesImport
      parentRoute: typeof rootRoute
    }
    '/products/permissions': {
      id: '/products/permissions'
      path: '/products/permissions'
      fullPath: '/products/permissions'
      preLoaderRoute: typeof ProductsPermissionsImport
      parentRoute: typeof rootRoute
    }
    '/products/product-api-keys': {
      id: '/products/product-api-keys'
      path: '/products/product-api-keys'
      fullPath: '/products/product-api-keys'
      preLoaderRoute: typeof ProductsProductApiKeysImport
      parentRoute: typeof rootRoute
    }
    '/products/product-resource-permissions': {
      id: '/products/product-resource-permissions'
      path: '/products/product-resource-permissions'
      fullPath: '/products/product-resource-permissions'
      preLoaderRoute: typeof ProductsProductResourcePermissionsImport
      parentRoute: typeof rootRoute
    }
    '/products/product-roles-route': {
      id: '/products/product-roles-route'
      path: '/products/product-roles-route'
      fullPath: '/products/product-roles-route'
      preLoaderRoute: typeof ProductsProductRolesRouteImport
      parentRoute: typeof rootRoute
    }
    '/products/product-users': {
      id: '/products/product-users'
      path: '/products/product-users'
      fullPath: '/products/product-users'
      preLoaderRoute: typeof ProductsProductUsersImport
      parentRoute: typeof rootRoute
    }
    '/products/products': {
      id: '/products/products'
      path: '/products/products'
      fullPath: '/products/products'
      preLoaderRoute: typeof ProductsProductsImport
      parentRoute: typeof rootRoute
    }
    '/settings/app': {
      id: '/settings/app'
      path: '/settings/app'
      fullPath: '/settings/app'
      preLoaderRoute: typeof SettingsAppImport
      parentRoute: typeof rootRoute
    }
    '/settings/user': {
      id: '/settings/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof SettingsUserImport
      parentRoute: typeof rootRoute
    }
    '/platform/$productId/integration-clerk': {
      id: '/platform/$productId/integration-clerk'
      path: '/platform/$productId/integration-clerk'
      fullPath: '/platform/$productId/integration-clerk'
      preLoaderRoute: typeof PlatformProductIdIntegrationClerkImport
      parentRoute: typeof rootRoute
    }
    '/platform/$productId/integration-smtp': {
      id: '/platform/$productId/integration-smtp'
      path: '/platform/$productId/integration-smtp'
      fullPath: '/platform/$productId/integration-smtp'
      preLoaderRoute: typeof PlatformProductIdIntegrationSmtpImport
      parentRoute: typeof rootRoute
    }
    '/platform/$productId/integrations': {
      id: '/platform/$productId/integrations'
      path: '/platform/$productId/integrations'
      fullPath: '/platform/$productId/integrations'
      preLoaderRoute: typeof PlatformProductIdIntegrationsImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId/edit': {
      id: '/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizations/organization-api-keys': typeof OrganizationsOrganizationApiKeysRoute
  '/organizations/organization-memberships': typeof OrganizationsOrganizationMembershipsRoute
  '/organizations/organizations': typeof OrganizationsOrganizationsRoute
  '/organizations/workspace-memberships': typeof OrganizationsWorkspaceMembershipsRoute
  '/organizations/workspaces': typeof OrganizationsWorkspacesRoute
  '/platform/init': typeof PlatformInitRoute
  '/platform/integration-clerk': typeof PlatformIntegrationClerkRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/invitations': typeof PlatformInvitationsRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/platform-users': typeof PlatformPlatformUsersRoute
  '/platform/register': typeof PlatformRegisterRoute
  '/products/email-sends': typeof ProductsEmailSendsRoute
  '/products/email-template-builder': typeof ProductsEmailTemplateBuilderRoute
  '/products/email-templates': typeof ProductsEmailTemplatesRoute
  '/products/permissions': typeof ProductsPermissionsRoute
  '/products/product-api-keys': typeof ProductsProductApiKeysRoute
  '/products/product-resource-permissions': typeof ProductsProductResourcePermissionsRoute
  '/products/product-roles-route': typeof ProductsProductRolesRouteRoute
  '/products/product-users': typeof ProductsProductUsersRoute
  '/products/products': typeof ProductsProductsRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/user': typeof SettingsUserRoute
  '/platform/$productId/integration-clerk': typeof PlatformProductIdIntegrationClerkRoute
  '/platform/$productId/integration-smtp': typeof PlatformProductIdIntegrationSmtpRoute
  '/platform/$productId/integrations': typeof PlatformProductIdIntegrationsRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizations/organization-api-keys': typeof OrganizationsOrganizationApiKeysRoute
  '/organizations/organization-memberships': typeof OrganizationsOrganizationMembershipsRoute
  '/organizations/organizations': typeof OrganizationsOrganizationsRoute
  '/organizations/workspace-memberships': typeof OrganizationsWorkspaceMembershipsRoute
  '/organizations/workspaces': typeof OrganizationsWorkspacesRoute
  '/platform/init': typeof PlatformInitRoute
  '/platform/integration-clerk': typeof PlatformIntegrationClerkRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/invitations': typeof PlatformInvitationsRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/platform-users': typeof PlatformPlatformUsersRoute
  '/platform/register': typeof PlatformRegisterRoute
  '/products/email-sends': typeof ProductsEmailSendsRoute
  '/products/email-template-builder': typeof ProductsEmailTemplateBuilderRoute
  '/products/email-templates': typeof ProductsEmailTemplatesRoute
  '/products/permissions': typeof ProductsPermissionsRoute
  '/products/product-api-keys': typeof ProductsProductApiKeysRoute
  '/products/product-resource-permissions': typeof ProductsProductResourcePermissionsRoute
  '/products/product-roles-route': typeof ProductsProductRolesRouteRoute
  '/products/product-users': typeof ProductsProductUsersRoute
  '/products/products': typeof ProductsProductsRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/user': typeof SettingsUserRoute
  '/platform/$productId/integration-clerk': typeof PlatformProductIdIntegrationClerkRoute
  '/platform/$productId/integration-smtp': typeof PlatformProductIdIntegrationSmtpRoute
  '/platform/$productId/integrations': typeof PlatformProductIdIntegrationsRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/organizations/organization-api-keys': typeof OrganizationsOrganizationApiKeysRoute
  '/organizations/organization-memberships': typeof OrganizationsOrganizationMembershipsRoute
  '/organizations/organizations': typeof OrganizationsOrganizationsRoute
  '/organizations/workspace-memberships': typeof OrganizationsWorkspaceMembershipsRoute
  '/organizations/workspaces': typeof OrganizationsWorkspacesRoute
  '/platform/init': typeof PlatformInitRoute
  '/platform/integration-clerk': typeof PlatformIntegrationClerkRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/invitations': typeof PlatformInvitationsRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/platform-users': typeof PlatformPlatformUsersRoute
  '/platform/register': typeof PlatformRegisterRoute
  '/products/email-sends': typeof ProductsEmailSendsRoute
  '/products/email-template-builder': typeof ProductsEmailTemplateBuilderRoute
  '/products/email-templates': typeof ProductsEmailTemplatesRoute
  '/products/permissions': typeof ProductsPermissionsRoute
  '/products/product-api-keys': typeof ProductsProductApiKeysRoute
  '/products/product-resource-permissions': typeof ProductsProductResourcePermissionsRoute
  '/products/product-roles-route': typeof ProductsProductRolesRouteRoute
  '/products/product-users': typeof ProductsProductUsersRoute
  '/products/products': typeof ProductsProductsRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/user': typeof SettingsUserRoute
  '/platform/$productId/integration-clerk': typeof PlatformProductIdIntegrationClerkRoute
  '/platform/$productId/integration-smtp': typeof PlatformProductIdIntegrationSmtpRoute
  '/platform/$productId/integrations': typeof PlatformProductIdIntegrationsRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations/organization-api-keys'
    | '/organizations/organization-memberships'
    | '/organizations/organizations'
    | '/organizations/workspace-memberships'
    | '/organizations/workspaces'
    | '/platform/init'
    | '/platform/integration-clerk'
    | '/platform/integrations'
    | '/platform/invitations'
    | '/platform/login'
    | '/platform/platform-users'
    | '/platform/register'
    | '/products/email-sends'
    | '/products/email-template-builder'
    | '/products/email-templates'
    | '/products/permissions'
    | '/products/product-api-keys'
    | '/products/product-resource-permissions'
    | '/products/product-roles-route'
    | '/products/product-users'
    | '/products/products'
    | '/settings/app'
    | '/settings/user'
    | '/platform/$productId/integration-clerk'
    | '/platform/$productId/integration-smtp'
    | '/platform/$productId/integrations'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizations/organization-api-keys'
    | '/organizations/organization-memberships'
    | '/organizations/organizations'
    | '/organizations/workspace-memberships'
    | '/organizations/workspaces'
    | '/platform/init'
    | '/platform/integration-clerk'
    | '/platform/integrations'
    | '/platform/invitations'
    | '/platform/login'
    | '/platform/platform-users'
    | '/platform/register'
    | '/products/email-sends'
    | '/products/email-template-builder'
    | '/products/email-templates'
    | '/products/permissions'
    | '/products/product-api-keys'
    | '/products/product-resource-permissions'
    | '/products/product-roles-route'
    | '/products/product-users'
    | '/products/products'
    | '/settings/app'
    | '/settings/user'
    | '/platform/$productId/integration-clerk'
    | '/platform/$productId/integration-smtp'
    | '/platform/$productId/integrations'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/organizations/organization-api-keys'
    | '/organizations/organization-memberships'
    | '/organizations/organizations'
    | '/organizations/workspace-memberships'
    | '/organizations/workspaces'
    | '/platform/init'
    | '/platform/integration-clerk'
    | '/platform/integrations'
    | '/platform/invitations'
    | '/platform/login'
    | '/platform/platform-users'
    | '/platform/register'
    | '/products/email-sends'
    | '/products/email-template-builder'
    | '/products/email-templates'
    | '/products/permissions'
    | '/products/product-api-keys'
    | '/products/product-resource-permissions'
    | '/products/product-roles-route'
    | '/products/product-users'
    | '/products/products'
    | '/settings/app'
    | '/settings/user'
    | '/platform/$productId/integration-clerk'
    | '/platform/$productId/integration-smtp'
    | '/platform/$productId/integrations'
    | '/products/$productId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationsOrganizationApiKeysRoute: typeof OrganizationsOrganizationApiKeysRoute
  OrganizationsOrganizationMembershipsRoute: typeof OrganizationsOrganizationMembershipsRoute
  OrganizationsOrganizationsRoute: typeof OrganizationsOrganizationsRoute
  OrganizationsWorkspaceMembershipsRoute: typeof OrganizationsWorkspaceMembershipsRoute
  OrganizationsWorkspacesRoute: typeof OrganizationsWorkspacesRoute
  PlatformInitRoute: typeof PlatformInitRoute
  PlatformIntegrationClerkRoute: typeof PlatformIntegrationClerkRoute
  PlatformIntegrationsRoute: typeof PlatformIntegrationsRoute
  PlatformInvitationsRoute: typeof PlatformInvitationsRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  PlatformPlatformUsersRoute: typeof PlatformPlatformUsersRoute
  PlatformRegisterRoute: typeof PlatformRegisterRoute
  ProductsEmailSendsRoute: typeof ProductsEmailSendsRoute
  ProductsEmailTemplateBuilderRoute: typeof ProductsEmailTemplateBuilderRoute
  ProductsEmailTemplatesRoute: typeof ProductsEmailTemplatesRoute
  ProductsPermissionsRoute: typeof ProductsPermissionsRoute
  ProductsProductApiKeysRoute: typeof ProductsProductApiKeysRoute
  ProductsProductResourcePermissionsRoute: typeof ProductsProductResourcePermissionsRoute
  ProductsProductRolesRouteRoute: typeof ProductsProductRolesRouteRoute
  ProductsProductUsersRoute: typeof ProductsProductUsersRoute
  ProductsProductsRoute: typeof ProductsProductsRoute
  SettingsAppRoute: typeof SettingsAppRoute
  SettingsUserRoute: typeof SettingsUserRoute
  PlatformProductIdIntegrationClerkRoute: typeof PlatformProductIdIntegrationClerkRoute
  PlatformProductIdIntegrationSmtpRoute: typeof PlatformProductIdIntegrationSmtpRoute
  PlatformProductIdIntegrationsRoute: typeof PlatformProductIdIntegrationsRoute
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationsOrganizationApiKeysRoute: OrganizationsOrganizationApiKeysRoute,
  OrganizationsOrganizationMembershipsRoute:
    OrganizationsOrganizationMembershipsRoute,
  OrganizationsOrganizationsRoute: OrganizationsOrganizationsRoute,
  OrganizationsWorkspaceMembershipsRoute:
    OrganizationsWorkspaceMembershipsRoute,
  OrganizationsWorkspacesRoute: OrganizationsWorkspacesRoute,
  PlatformInitRoute: PlatformInitRoute,
  PlatformIntegrationClerkRoute: PlatformIntegrationClerkRoute,
  PlatformIntegrationsRoute: PlatformIntegrationsRoute,
  PlatformInvitationsRoute: PlatformInvitationsRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  PlatformPlatformUsersRoute: PlatformPlatformUsersRoute,
  PlatformRegisterRoute: PlatformRegisterRoute,
  ProductsEmailSendsRoute: ProductsEmailSendsRoute,
  ProductsEmailTemplateBuilderRoute: ProductsEmailTemplateBuilderRoute,
  ProductsEmailTemplatesRoute: ProductsEmailTemplatesRoute,
  ProductsPermissionsRoute: ProductsPermissionsRoute,
  ProductsProductApiKeysRoute: ProductsProductApiKeysRoute,
  ProductsProductResourcePermissionsRoute:
    ProductsProductResourcePermissionsRoute,
  ProductsProductRolesRouteRoute: ProductsProductRolesRouteRoute,
  ProductsProductUsersRoute: ProductsProductUsersRoute,
  ProductsProductsRoute: ProductsProductsRoute,
  SettingsAppRoute: SettingsAppRoute,
  SettingsUserRoute: SettingsUserRoute,
  PlatformProductIdIntegrationClerkRoute:
    PlatformProductIdIntegrationClerkRoute,
  PlatformProductIdIntegrationSmtpRoute: PlatformProductIdIntegrationSmtpRoute,
  PlatformProductIdIntegrationsRoute: PlatformProductIdIntegrationsRoute,
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/organizations/organization-api-keys",
        "/organizations/organization-memberships",
        "/organizations/organizations",
        "/organizations/workspace-memberships",
        "/organizations/workspaces",
        "/platform/init",
        "/platform/integration-clerk",
        "/platform/integrations",
        "/platform/invitations",
        "/platform/login",
        "/platform/platform-users",
        "/platform/register",
        "/products/email-sends",
        "/products/email-template-builder",
        "/products/email-templates",
        "/products/permissions",
        "/products/product-api-keys",
        "/products/product-resource-permissions",
        "/products/product-roles-route",
        "/products/product-users",
        "/products/products",
        "/settings/app",
        "/settings/user",
        "/platform/$productId/integration-clerk",
        "/platform/$productId/integration-smtp",
        "/platform/$productId/integrations",
        "/products/$productId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/organizations/organization-api-keys": {
      "filePath": "organizations/organization-api-keys.tsx"
    },
    "/organizations/organization-memberships": {
      "filePath": "organizations/organization-memberships.tsx"
    },
    "/organizations/organizations": {
      "filePath": "organizations/organizations.tsx"
    },
    "/organizations/workspace-memberships": {
      "filePath": "organizations/workspace-memberships.tsx"
    },
    "/organizations/workspaces": {
      "filePath": "organizations/workspaces.tsx"
    },
    "/platform/init": {
      "filePath": "platform/init.tsx"
    },
    "/platform/integration-clerk": {
      "filePath": "platform/integration-clerk.tsx"
    },
    "/platform/integrations": {
      "filePath": "platform/integrations.tsx"
    },
    "/platform/invitations": {
      "filePath": "platform/invitations.tsx"
    },
    "/platform/login": {
      "filePath": "platform/login.tsx"
    },
    "/platform/platform-users": {
      "filePath": "platform/platform-users.tsx"
    },
    "/platform/register": {
      "filePath": "platform/register.tsx"
    },
    "/products/email-sends": {
      "filePath": "products/email-sends.tsx"
    },
    "/products/email-template-builder": {
      "filePath": "products/email-template-builder.tsx"
    },
    "/products/email-templates": {
      "filePath": "products/email-templates.tsx"
    },
    "/products/permissions": {
      "filePath": "products/permissions.tsx"
    },
    "/products/product-api-keys": {
      "filePath": "products/product-api-keys.tsx"
    },
    "/products/product-resource-permissions": {
      "filePath": "products/product-resource-permissions.tsx"
    },
    "/products/product-roles-route": {
      "filePath": "products/product-roles-route.tsx"
    },
    "/products/product-users": {
      "filePath": "products/product-users.tsx"
    },
    "/products/products": {
      "filePath": "products/products.tsx"
    },
    "/settings/app": {
      "filePath": "settings/app.tsx"
    },
    "/settings/user": {
      "filePath": "settings/user.tsx"
    },
    "/platform/$productId/integration-clerk": {
      "filePath": "platform/$productId.integration-clerk.tsx"
    },
    "/platform/$productId/integration-smtp": {
      "filePath": "platform/$productId.integration-smtp.tsx"
    },
    "/platform/$productId/integrations": {
      "filePath": "platform/$productId.integrations.tsx"
    },
    "/products/$productId/edit": {
      "filePath": "products/$productId.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
