import { WorkflowFieldType } from "@/client";
import {
	AtSign,
	BadgeCheck,
	Braces,
	Building2,
	CalendarClock,
	FileBadge,
	Hash,
	KeyRound,
	LayoutGrid,
	Link,
	ListChecks,
	type LucideIcon,
	MailPlus,
	Shield,
	ToggleLeft,
	Type,
	User,
} from "lucide-react";

export const fieldTypeIcons: Record<WorkflowFieldType, LucideIcon> = {
	[WorkflowFieldType.TEXT]: Type,
	[WorkflowFieldType.EMAIL]: AtSign,
	[WorkflowFieldType.NUMBER]: Hash,
	[WorkflowFieldType.BOOLEAN]: ToggleLeft,
	[WorkflowFieldType.TIMESTAMP]: CalendarClock,
	[WorkflowFieldType.URL]: Link,
	[WorkflowFieldType.JSON]: Braces,
	[WorkflowFieldType.ORGANIZATION]: Building2,
	[WorkflowFieldType.WORKSPACE]: LayoutGrid,
	[WorkflowFieldType.PRODUCT_USER]: User,
	[WorkflowFieldType.INVITATION]: MailPlus,
	[WorkflowFieldType.API_KEY]: KeyRound,
	[WorkflowFieldType.ROLE]: Shield,
	[WorkflowFieldType.PERMISSION]: ListChecks,
	[WorkflowFieldType.LICENSE]: BadgeCheck,
	[WorkflowFieldType.LICENSE_TEMPLATE]: FileBadge,
};
