import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
	checkCoverageDocument,
	discoverCoverage,
	updateCoverageDocument,
} from "./e2e-coverage.mjs";

const root = path.resolve(import.meta.dirname, "..");
function files(directory) {
	return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
		const full = path.join(directory, entry.name);
		return entry.isDirectory()
			? files(full)
			: full.endsWith(".e2e.ts")
				? [full]
				: [];
	});
}
const routes = [
	...readFileSync(path.join(root, "src/routes/routePaths.ts"), "utf8").matchAll(
		/^\s*([A-Z_]+):\s*\n?\s*"([^"]+)"/gm,
	),
].map((match) => ({ key: match[1], route: match[2] }));
const coverage = new Map(routes.map((route) => [route.key, []]));
const errors = [];
const specs = files(path.join(root, "e2e/features")).sort();
for (const file of specs) {
	const source = readFileSync(file, "utf8");
	const relative = path.relative(root, file).split(path.sep).join("/");
	if (/\btest(?:\.describe)?\.(?:skip|fixme|only)\s*\(/.test(source))
		errors.push(
			`${relative}: skipped, fixed or focused cases cannot count as verified coverage`,
		);
	if (/waitForTimeout\s*\(|["']networkidle["']|force:\s*true/.test(source))
		errors.push(`${relative}: use observable readiness and actionability`);
	const keys = new Set(
		[...source.matchAll(/^\s*\/\/ Covers:\s*(.+)$/gm)].flatMap((match) =>
			match[1].split(",").map((key) => key.trim()),
		),
	);
	if (keys.size === 0)
		errors.push(`${relative}: add Covers annotations for the route exercised`);
	for (const key of keys) {
		if (!coverage.has(key))
			errors.push(`${relative}: unknown route key ${key}`);
		else coverage.get(key).push(relative);
	}
}
for (const [key, owners] of coverage)
	if (owners.length === 0)
		errors.push(`${key}: route has no linked browser scenario`);
const generated = `# Route to browser scenario map\n\nGenerated by \`pnpm check:e2e --write\`. This checks inventory drift; it is not a code-coverage percentage. Run the scenarios and maintain [coverage.md](coverage.md) to verify behavior.\n\n| Route key | Shipped route | Scenarios |\n| --- | --- | --- |\n${routes
	.map(
		({ key, route }) =>
			`| ${key} | \`${route}\` | ${coverage
				.get(key)
				.map(
					(file) =>
						`[${file.replace("e2e/features/", "")}](../${file.slice(4)})`,
				)
				.join(", ")} |`,
	)
	.join("\n")}\n`;
const destination = path.join(root, "e2e/guide/routes.generated.md");
if (process.argv.includes("--write")) writeFileSync(destination, generated);
else {
	let existing;
	try {
		existing = readFileSync(destination, "utf8");
	} catch {
		/* Report the missing generated inventory below. */
	}
	if (existing !== generated)
		errors.push(
			"Route map changed: run pnpm check:e2e --write and review the coverage matrix",
		);
}
try {
	const guidePath = path.join(root, "e2e/guide/coverage.md");
	const summary = await discoverCoverage();
	const document = readFileSync(guidePath, "utf8");
	if (process.argv.includes("--write"))
		writeFileSync(guidePath, updateCoverageDocument(document, summary));
	else checkCoverageDocument(document, summary);
} catch (error) {
	errors.push(error.message);
}
if (errors.length) {
	console.error(errors.join("\n"));
	process.exitCode = 1;
} else
	console.log(
		`E2E inventory: ${routes.length} routes linked across ${specs.length} specs; no excluded scenarios or fixed waits.`,
	);
