// Package billing provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package billing

import (
	"time"
)

// Defines values for AccountMode.
const (
	Sandbox AccountMode = "sandbox"
)

// Valid indicates whether the value is a known member of the AccountMode enum.
func (e AccountMode) Valid() bool {
	switch e {
	case Sandbox:
		return true
	default:
		return false
	}
}

// Defines values for CreatePriceRequestCurrency.
const (
	CreatePriceRequestCurrencyCad CreatePriceRequestCurrency = "cad"
	CreatePriceRequestCurrencyEur CreatePriceRequestCurrency = "eur"
	CreatePriceRequestCurrencyUsd CreatePriceRequestCurrency = "usd"
)

// Valid indicates whether the value is a known member of the CreatePriceRequestCurrency enum.
func (e CreatePriceRequestCurrency) Valid() bool {
	switch e {
	case CreatePriceRequestCurrencyCad:
		return true
	case CreatePriceRequestCurrencyEur:
		return true
	case CreatePriceRequestCurrencyUsd:
		return true
	default:
		return false
	}
}

// Defines values for CreatePriceRequestInterval.
const (
	CreatePriceRequestIntervalMonth CreatePriceRequestInterval = "month"
	CreatePriceRequestIntervalYear  CreatePriceRequestInterval = "year"
)

// Valid indicates whether the value is a known member of the CreatePriceRequestInterval enum.
func (e CreatePriceRequestInterval) Valid() bool {
	switch e {
	case CreatePriceRequestIntervalMonth:
		return true
	case CreatePriceRequestIntervalYear:
		return true
	default:
		return false
	}
}

// Defines values for PriceCurrency.
const (
	PriceCurrencyCad PriceCurrency = "cad"
	PriceCurrencyEur PriceCurrency = "eur"
	PriceCurrencyUsd PriceCurrency = "usd"
)

// Valid indicates whether the value is a known member of the PriceCurrency enum.
func (e PriceCurrency) Valid() bool {
	switch e {
	case PriceCurrencyCad:
		return true
	case PriceCurrencyEur:
		return true
	case PriceCurrencyUsd:
		return true
	default:
		return false
	}
}

// Defines values for PriceInterval.
const (
	PriceIntervalMonth PriceInterval = "month"
	PriceIntervalYear  PriceInterval = "year"
)

// Valid indicates whether the value is a known member of the PriceInterval enum.
func (e PriceInterval) Valid() bool {
	switch e {
	case PriceIntervalMonth:
		return true
	case PriceIntervalYear:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	ID   string      `json:"id"`
	Mode AccountMode `json:"mode"`
	Name string      `json:"name"`
}

// AccountMode defines model for Account.Mode.
type AccountMode string

// BillingEvent defines model for BillingEvent.
type BillingEvent struct {
	ID             string    `json:"id"`
	LastError      string    `json:"last_error"`
	OrganizationID string    `json:"organization_id"`
	ReceivedAt     time.Time `json:"received_at"`
	Status         string    `json:"status"`
	Type           string    `json:"type"`
}

// CheckoutRequest defines model for CheckoutRequest.
type CheckoutRequest struct {
	PriceID   Identifier `json:"price_id"`
	TrialDays int        `json:"trial_days"`
}

// CreatePriceRequest defines model for CreatePriceRequest.
type CreatePriceRequest struct {
	Amount     int64                      `json:"amount"`
	Currency   CreatePriceRequestCurrency `json:"currency"`
	Interval   CreatePriceRequestInterval `json:"interval"`
	Name       string                     `json:"name"`
	TemplateID Identifier                 `json:"template_id"`
}

// CreatePriceRequestCurrency defines model for CreatePriceRequest.Currency.
type CreatePriceRequestCurrency string

// CreatePriceRequestInterval defines model for CreatePriceRequest.Interval.
type CreatePriceRequestInterval string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Identifier defines model for Identifier.
type Identifier = string

// Organization defines model for Organization.
type Organization struct {
	CancelAtPeriodEnd bool                   `json:"cancel_at_period_end"`
	CurrentPeriodEnd  *time.Time             `json:"current_period_end"`
	CustomerID        string                 `json:"customer_id"`
	ID                Identifier             `json:"id"`
	LastSyncedAt      *time.Time             `json:"last_synced_at"`
	LicenseValues     map[string]interface{} `json:"license_values"`
	Name              string                 `json:"name"`
	PendingUpdate     bool                   `json:"pending_update"`
	PriceID           string                 `json:"price_id"`
	Status            string                 `json:"status"`
	SubscriptionID    string                 `json:"subscription_id"`
	SyncError         string                 `json:"sync_error"`
	SyncState         string                 `json:"sync_state"`
	TemplateID        string                 `json:"template_id"`
}

// Price defines model for Price.
type Price struct {
	Active bool `json:"active"`

	// Amount Recurring amount in the smallest unit of the currency
	Amount          int64         `json:"amount"`
	Currency        PriceCurrency `json:"currency"`
	ID              Identifier    `json:"id"`
	Interval        PriceInterval `json:"interval"`
	Name            string        `json:"name"`
	StripePriceID   string        `json:"stripe_price_id"`
	StripeProductID string        `json:"stripe_product_id"`
	TemplateID      Identifier    `json:"template_id"`
}

// PriceCurrency defines model for Price.Currency.
type PriceCurrency string

// PriceInterval defines model for Price.Interval.
type PriceInterval string

// Product defines model for Product.
type Product struct {
	ID   Identifier `json:"id"`
	Name string     `json:"name"`
}

// Settings defines model for Settings.
type Settings struct {
	FallbackTemplateID Identifier `json:"fallback_template_id"`
}

// State defines model for State.
type State struct {
	Account       Account        `json:"account"`
	Events        []BillingEvent `json:"events"`
	Organizations []Organization `json:"organizations"`
	Prices        []Price        `json:"prices"`
	Product       Product        `json:"product"`
	Settings      Settings       `json:"settings"`
	Templates     []Template     `json:"templates"`
}

// SubscriptionRequest defines model for SubscriptionRequest.
type SubscriptionRequest struct {
	PriceID Identifier `json:"price_id"`
}

// Template defines model for Template.
type Template struct {
	Archived bool                   `json:"archived"`
	ID       Identifier             `json:"id"`
	Name     string                 `json:"name"`
	Values   map[string]interface{} `json:"values"`
}

// URLResponse defines model for URLResponse.
type URLResponse struct {
	URL string `json:"url"`
}

// UpdateSettingsRequest defines model for UpdateSettingsRequest.
type UpdateSettingsRequest struct {
	FallbackTemplateID Identifier `json:"fallback_template_id"`
}

// WebhookResponse defines model for WebhookResponse.
type WebhookResponse struct {
	Received bool `json:"received"`
}
